version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      -  data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  msvc-usuarios:
    container_name: msvc-usuarios
    image: juanaguero32/usuarios
#    build:
#     context: ./
#     dockerfile: ./mscv-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT : 8001
      DB_HOST : mysql8:3306
      DB_DATABASE : msvc_usuarios
      DB_USERNAME : root
      DB_PASSWORD : root
      CURSOS_URL : ec2-52-23-166-228.compute-1.amazonaws.com:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

volumes:
  data-mysql:
    name: data-mysql


networks:
  spring:



